# Generated by Django 4.2.7 on 2023-11-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_voters_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='voters',
            new_name='voter',
        ),
        migrations.AddField(
            model_name='voters',
            name='choise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
