# Generated by Django 4.2.7 on 2023-11-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_voters_voters_voter_voters_choise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='choise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
