# Generated by Django 4.2.7 on 2023-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/pics', verbose_name='картинка поста'),
        ),
    ]
