# Generated by Django 4.2.7 on 2023-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_description_question_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(verbose_name='Описание вопроса'),
        ),
    ]
